name = "Popcorn Gun"
description = "A weapon made by corn"
author = "ZombieJ"
version = "1"
api_version = 10
dst_compatible = true
dont_starve_compatible = true
reign_of_giants_compatible = true
restart_required = false
standalone = false